[package]
name = "hash"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5.0"
polymur-hash = "0.2.1"
rand = "0.8.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
umash = "0.4.1"
